# Generated by Django 4.0 on 2022-10-04 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profile_image',
        ),
    ]
