# Generated by Django 4.0 on 2022-10-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='requested_salary_slip',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
