# Generated by Django 4.0 on 2022-10-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_requested_salary_slip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='requested_salary_slip',
            field=models.FileField(blank=True, null=True, upload_to='monthly salaries'),
        ),
    ]
