# Generated by Django 4.0 on 2022-10-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_requested_salary_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cinic_back',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='cinic_front',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='time_slot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
