# Generated by Django 4.0 on 2022-10-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_cinic_back_employee_cinic_front_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cinic_back',
            field=models.FileField(blank=True, null=True, upload_to='cnic back'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cinic_front',
            field=models.FileField(blank=True, null=True, upload_to='cnic front'),
        ),
    ]
