# Generated by Django 4.0 on 2022-10-18 07:48

from django.db import migrations, models
import employee.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employee_cinic_back_alter_employee_cinic_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cinic_back',
            field=models.FileField(blank=True, null=True, upload_to='cnic back', validators=[employee.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cinic_front',
            field=models.FileField(blank=True, null=True, upload_to='cnic front', validators=[employee.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images', validators=[employee.validators.validate_file_size]),
        ),
    ]
