# Generated by Django 4.0 on 2023-01-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_checkin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'verbose_name_plural': 'Employee CheckIn'},
        ),
        migrations.AddField(
            model_name='employee',
            name='attendence_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
