# Generated by Django 4.0 on 2023-01-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_checkin_options_employee_attendence_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'verbose_name_plural': 'Attendence'},
        ),
        migrations.AddField(
            model_name='checkin',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('WFH', 'WFH')], default='Absent', max_length=15),
        ),
    ]
