# Generated by Django 4.0 on 2023-01-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_checkin_options_checkin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='time_slot',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
