# Generated by Django 4.0 on 2023-01-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_employee_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='checkin_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='time_slot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
