# Generated by Django 4.0 on 2023-01-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_checkin_checkin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='checkin_time',
            field=models.TimeField(blank=True, editable=False, null=True),
        ),
    ]
