# Generated by Django 4.0 on 2023-01-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_alter_employee_checkin_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee'},
        ),
    ]
