# Generated by Django 4.0 on 2023-01-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_annocument_date_time_annocument_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annocument',
            options={'verbose_name': 'Company Annoument'},
        ),
    ]
