# Generated by Django 4.0 on 2022-09-29 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Tax', 'Tax'), ('Fine', 'Fine'), ('Lunch', 'Lunch'), ('Other', 'Other')], default='Other', max_length=15)),
                ('amount', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('for_month_year', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Bonus', 'Bonus'), ('Medical', 'Medical'), ('Car Finance', 'Car Finance'), ('Extra Hours', 'Extra Hours'), ('House Allowance', 'House Allowance'), ('Other', 'Other')], default='Other', max_length=15)),
                ('amount', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('for_month_year', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('monthly_salary', models.IntegerField()),
                ('computed_salary', models.IntegerField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('for_month_year', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
