# Generated by Django 4.0 on 2022-09-29 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('times', models.IntegerField(default=1)),
                ('number_of_hours', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('0', 'PENDING'), ('1', 'APPROVED')], default='0', max_length=1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employee.employee')),
                ('report_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to='employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
